name: loka_word_builder
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flame: ^1.32.0
  flame_forge2d: ^0.19.2
  flame_audio: ^2.11.10
  flutter_tts: ^4.2.3
  audioplayers: ^6.1.0
  confetti: ^0.8.0
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/animals/
    - assets/levels/
    - assets/icon/
    - assets/sounds/success.mp3

flutter_launcher_name:
  name: "Loka Word Builder"

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  min_sdk_android: 21
